// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rema.DbAccess;

namespace Rema.DbAccess.Migrations
{
    [DbContext(typeof(RpDbContext))]
    partial class RpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rema.Infrastructure.Models.Allocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ApprovedById")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastModifiedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(3000)")
                        .HasMaxLength(3000);

                    b.Property<long?>("ReferencePersonId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RessourceId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ScheduleSeriesGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerializedHints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("ReferencePersonId");

                    b.HasIndex("RessourceId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("Rema.Infrastructure.Models.AllocationGagdet", b =>
                {
                    b.Property<long>("AllocationId")
                        .HasColumnType("bigint");

                    b.Property<long>("GadgetId")
                        .HasColumnType("bigint");

                    b.HasKey("AllocationId", "GadgetId");

                    b.HasIndex("GadgetId");

                    b.ToTable("AllocationGagdet");
                });

            modelBuilder.Entity("Rema.Infrastructure.Models.Gadget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("RessourceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SuppliedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RessourceId");

                    b.HasIndex("SuppliedById");

                    b.ToTable("Gadgets");
                });

            modelBuilder.Entity("Rema.Infrastructure.Models.Ressource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FunctionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpecialsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usability")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Ressources");
                });

            modelBuilder.Entity("Rema.Infrastructure.Models.SupplierGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("SupplierGroups");
                });

            modelBuilder.Entity("Rema.Infrastructure.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveDirectoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organisation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rema.Infrastructure.Models.Allocation", b =>
                {
                    b.HasOne("Rema.Infrastructure.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("Rema.Infrastructure.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rema.Infrastructure.Models.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("Rema.Infrastructure.Models.User", "ReferencePerson")
                        .WithMany()
                        .HasForeignKey("ReferencePersonId");

                    b.HasOne("Rema.Infrastructure.Models.Ressource", "Ressource")
                        .WithMany()
                        .HasForeignKey("RessourceId");
                });

            modelBuilder.Entity("Rema.Infrastructure.Models.AllocationGagdet", b =>
                {
                    b.HasOne("Rema.Infrastructure.Models.Allocation", "Allocation")
                        .WithMany("AllocationGadgets")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rema.Infrastructure.Models.Gadget", "Gadget")
                        .WithMany("AllocationGadgets")
                        .HasForeignKey("GadgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rema.Infrastructure.Models.Gadget", b =>
                {
                    b.HasOne("Rema.Infrastructure.Models.Ressource", null)
                        .WithMany("Gadgets")
                        .HasForeignKey("RessourceId");

                    b.HasOne("Rema.Infrastructure.Models.SupplierGroup", "SuppliedBy")
                        .WithMany()
                        .HasForeignKey("SuppliedById");
                });
#pragma warning restore 612, 618
        }
    }
}
