name: Build c# project
on:
  push:
    branches:
      - '**'
    paths-ignore:
    - 'README.md'
jobs:
  setup-csharp-project:
    name: build c#
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: init configs
        run: Copy-Item .\Rema.WebApi\appsettings.template .\Rema.WebApi\appsettings.json
        shell: pwsh

      - name: restore packages and build project
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet restore Rema.sln
      - run: dotnet build Rema.sln

      - name: Build publish files for WebApi
        run: dotnet publish Rema.WebApi -c Release --output ./Rema.WebApi/publish
      - name: 'Upload RemaWebApi Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: RemaWebApi
          path: ./Rema.WebApi/publish
          retention-days: 30

  setup-node-project:
    name: build webui
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: rema-app-vue/package-lock.json

      - run: npm -v
      - name: install dependencies 
        working-directory: ./rema-app-vue
        run: npm ci

      - name: build SPA
        working-directory: ./rema-app-vue
        run: npm run build
      - name: 'Upload web app artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: RemaUI
          path: ./rema-app-vue/dist/R*.zip

#      - name: build all
#        working-directory: ./rema-app-vue
#        run: npm run build-all
