name: Build c# project
on: 
  push:
    branches:
      - 'github-actions'
jobs:
  setup-project:
    name: build c#
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: init configs
        run: Copy-Item .\Rema.WebApi\appsettings.template .\Rema.WebApi\appsettings.json
        shell: pwsh

      - name: restore packages and build project
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet restore Rema.sln
      - run: dotnet build Rema.sln

#      - name: init web app project
#        working-directory: ./rema-app-vue
#        run: npm install
#      - name: build spa
#        working-directory: ./rema-app-vue
#        run: npm run build